doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    PlentaContaoJobsBasicBundle: ~

twig:
    form_themes: ['@PlentaContaoJobsBasic/forms/form_layout.html.twig']
    globals:
        backend_route: '%contao.backend.route_prefix%'