services:
    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\TlPlentaJobsBasicOffer:
        public: true
        arguments:
            - '@Plenta\ContaoJobsBasic\Helper\EmploymentType'
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.slug'

    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\TlPlentaJobsBasicJobLocation:
        public: true

    # Contao Hooks
    Plenta\ContaoJobsBasic\EventListener\Contao\DCA\SetPtableForContentListener:
        tags:
            - { name: contao.hook, hook: loadDataContainer, method: setPtableForContentListener, priority: 0 }
        arguments:
            - '@request_stack'
            - '@contao.routing.scope_matcher'
