services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $projectDir: '%kernel.project_dir%'

    Plenta\ContaoJobsBasic\:
        resource: ../../../../../src/Plenta/ContaoJobsBasic/*
        exclude: ../../../../../src/Plenta/ContaoJobsBasic/{Entity,Migrations,Resources,Tests}

    Plenta\ContaoJobsBasic\Helper\EmploymentType:
        class: Plenta\ContaoJobsBasic\Helper\EmploymentType
        arguments:
            - '@translator'