services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Plenta\ContaoJobsBasic\:
        resource: ../../../../../src/Plenta/ContaoJobsBasic/*
        exclude: ../../../../../src/Plenta/ContaoJobsBasic/{Entity,Migrations,Resources,Tests}

    Plenta\ContaoJobsBasic\Helper\EmploymentType:
        class: Plenta\ContaoJobsBasic\Helper\EmploymentType
        arguments:
            - '@translator'

    Plenta\ContaoJobsBasic\GoogleForJobs\GoogleForJobs:
        class: Plenta\ContaoJobsBasic\GoogleForJobs\GoogleForJobs
        arguments:
            - '@Doctrine\Persistence\ManagerRegistry'
            - '@contao.image.picture_factory'
            - '@contao.assets.files_context'
            - '%kernel.project_dir%'
